links:
  - http://www.bbc.co.uk/
  - http://www.devopsweekly.com/
  - http://thepihut.com/

local:
  - /path/to/image1
  - /path/to/image2

auth_links:
  - url: https://foo.bar.com/
    username_element_type: name
    username_element_name: username
    username: <username>
    password_element_type: name
    password_element_name: password
    password: <password>
  - url: https://bar.foo.com
    username_element_type: id
    username_element_name: email
    username: <email_address>
    password_element_type: password
    password_element_name: password
    password: <password>

sleep_time: 60
